[package]
name = "driver-gpkg"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
plenora-io-model = { path = "../plenora-io-model" }
plenora-io-core = { path = "../plenora-io-core" }
driver-common = { path = "../driver-common" }
arrow-array.workspace = true
arrow-schema.workspace = true
rusqlite.workspace = true
geo-types.workspace = true
serde_json.workspace = true
tempfile.workspace = true
