[package]
name = "driver-geoparquet"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
plenora-core = { path = "../plenora-core" }
plenora-io-core = { path = "../plenora-io-core" }
arrow-array.workspace = true
arrow-schema.workspace = true
parquet.workspace = true
geo-types.workspace = true
serde_json.workspace = true
tempfile.workspace = true
