[package]
name = "driver-geoparquet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
plenora-io-model = { path = "../plenora-io-model" }
plenora-io-core = { path = "../plenora-io-core" }
driver-common = { path = "../driver-common" }
arrow-array.workspace = true
arrow-schema.workspace = true
jsonschema.workspace = true
parquet.workspace = true
base64.workspace = true
geo-types.workspace = true
serde_json.workspace = true
tempfile.workspace = true
