[package]
name = "driver-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
plenora-io-model = { path = "../plenora-io-model" }
arrow-array.workspace = true
arrow-schema.workspace = true
arrow-ipc.workspace = true
serde_json.workspace = true
wkt.workspace = true
