[package]
name = "plenora-io-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
plenora-io-model = { path = "../plenora-io-model" }
arrow-array.workspace = true
arrow-ipc.workspace = true
arrow-schema.workspace = true
serde = { workspace = true }
tempfile.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "android", target_vendor = "apple"))'.dependencies]
rustix.workspace = true

[target.'cfg(windows)'.dependencies]
atomicwrites.workspace = true
