[package]
name = "driver-ipc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
plenora-io-model = { path = "../plenora-io-model" }
plenora-io-core = { path = "../plenora-io-core" }
arrow-array.workspace = true
arrow-schema.workspace = true
arrow-ipc.workspace = true
tempfile.workspace = true

[dev-dependencies]
geo-types.workspace = true
